"storage": {
  s3: {
    type: "file",
    connection: "s3a://twitter-data",
    workspaces: {
      "root": {
        "location": "/",
        "writable": false,
        "defaultInputFormat": null,
        "allowAccessOutsideWorkspace": false
      }
    },
    formats: {
      "parquet": {
        "type": "parquet",
        "autoCorrectCorruptDates": true
      },
      "json": {
        "type": "json",
        "extensions": ["json"]
      },
      "csv" : {
        "type" : "text",
        "extensions" : [ "csv" ],
        "extractHeader" : true,
        "delimiter" : ",",
        "lineDelimiter" : "\n"
      }
    },
    enabled: true
  }
}